### ISSUE TITLE
airflow initdb error

### ISSUE THREAD

**Issue by bugbeta** [miho120/ambari-airflow-mpack#13]
[root@wsjylog03 ~]# airflow initdb                        
[2018-09-26 10:50:31,727] {__init__.py:45} INFO - Using executor LocalExecutor
DB: mysql://airflow:***@10.10.1.12/airflow
[2018-09-26 10:50:31,887] {db.py:312} INFO - Creating tables
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/usr/bin/airflow", line 28, in <module>
    args.func(args)
  File "/usr/lib/python2.7/site-packages/airflow/bin/cli.py", line 897, in initdb
    db_utils.initdb()
  File "/usr/lib/python2.7/site-packages/airflow/utils/db.py", line 114, in initdb
    schema='airflow_ci'))
  File "<string>", line 4, in __init__
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 424, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 421, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/lib/python2.7/site-packages/airflow/models.py", line 578, in __init__
    self.extra = extra
  File "<string>", line 1, in __set__
  File "/usr/lib/python2.7/site-packages/airflow/models.py", line 639, in set_extra
    fernet = get_fernet()
  File "/usr/lib/python2.7/site-packages/airflow/models.py", line 105, in get_fernet
    return Fernet(configuration.get('core', 'FERNET_KEY').encode('utf-8'))
  File "/usr/lib64/python2.7/site-packages/cryptography/fernet.py", line 34, in __init__
    key = base64.urlsafe_b64decode(key)
  File "/usr/lib64/python2.7/base64.py", line 112, in urlsafe_b64decode
    return b64decode(s, '-_')
  File "/usr/lib64/python2.7/base64.py", line 76, in b64decode
    raise TypeError(msg)

modify  /var/lib/ambari-server/resources/common-services/AIRFLOW/1.9.0/configuration/airflow-core-site.xml
from "mMGXRdfFpdUZDYmt8Ur1xVmspyOkYKtBlkv91dB8SVs" to "mMGXRdfFpdUZDYmt8Ur1xVmspyOkYKtBlkv91dB8SVs="
  <property>
    <name>fernet_key</name>
    <value>mMGXRdfFpdUZDYmt8Ur1xVmspyOkYKtBlkv91dB8SVs=</value>
    <display-name>Fernet key</display-name>
    <description>Secret key to save connection passwords in the db.</description>
  </property>

**Comment by miho120** [comment]
Hi @bugbeta,
Thanks for letting me know. Typo has been fixed in commit 575ac63.
