### ISSUE TITLE
Error while trying to install the service on Ambari HDP 2.6

### ISSUE THREAD

**Issue by BogdanCojocar** [miho120/ambari-airflow-mpack#14]
Installation error on Ambari:

`Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/common-services/AIRFLOW/1.10.0/package/scripts/airflow_scheduler_control.py", line 55, in <module>
    AirflowScheduler().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 367, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/common-services/AIRFLOW/1.10.0/package/scripts/airflow_scheduler_control.py", line 16, in install
    Execute(format("export SLUGIFY_USES_TEXT_UNIDECODE=yes && pip install --upgrade {airflow_pip_params} pip && pip install --upgrade {airflow_pip_params} docutils pytest-runner && pip install --upgrade {airflow_pip_params} --ignore-installed apache-airflow[all]==1.10.0 apache-airflow[celery]==1.10.0"))
  File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 166, in __init__
    self.env.run()
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/system.py", line 262, in action_run
    tries=self.resource.tries, try_sleep=self.resource.try_sleep)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 72, in inner
    result = function(command, **kwargs)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 102, in checked_call
    tries=tries, try_sleep=try_sleep, timeout_kill_strategy=timeout_kill_strategy)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 150, in _call_wrapper
    result = _call(command, **kwargs_copy)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 303, in _call
    raise ExecutionFailed(err_msg, code, out, err)
resource_management.core.exceptions.ExecutionFailed: Execution of 'export SLUGIFY_USES_TEXT_UNIDECODE=yes && pip install --upgrade  pip && pip install --upgrade  docutils pytest-runner && pip install --upgrade  --ignore-installed apache-airflow[all]==1.10.0 apache-airflow[celery]==1.10.0' returned 1. Requirement already up-to-date: pip in /usr/local/lib/python2.7/site-packages (18.0)
Collecting docutils
  Using cached https://files.pythonhosted.org/packages/50/09/c53398e0005b11f7ffb27b7aa720c617aba53be4fb4f4f3f06b9b5c60f28/docutils-0.14-py2-none-any.whl
Collecting pytest-runner
  Using cached https://files.pythonhosted.org/packages/72/a4/d7a5738a3096f22a98bec1609e237b250ebff04e5ea2930305d485337263/pytest_runner-4.2-py2.py3-none-any.whl
Installing collected packages: docutils, pytest-runner
  Found existing installation: docutils 0.11
Cannot uninstall 'docutils'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
`

**Comment by BogdanCojocar** [comment]
Thanks @miho120 for your reply. It's a strange issue because on Ambari we are using python 2.6, but if I ssh into the cluster python 2.7 is used. I'll investigate and let you know how it goes.

**Comment by praveennair19** [comment]
hi , 

i have a similar issue. I have my ambari setup on virtualbox. its failing with below error. The python version i am using is 2.7.

below is the complete error msg:

Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/common-services/AIRFLOW/1.10.0/package/scripts/airflow_scheduler_control.py", line 61, in <module>
    AirflowScheduler().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 353, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/common-services/AIRFLOW/1.10.0/package/scripts/airflow_scheduler_control.py", line 19, in install
    Execute(format("export SLUGIFY_USES_TEXT_UNIDECODE=yes && pip install --upgrade {airflow_pip_params} --ignore-installed apache-airflow[all]==1.10.0"))
  File "/usr/lib/ambari-agent/lib/resource_management/core/base.py", line 166, in __init__
    self.env.run()
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/ambari-agent/lib/resource_management/core/providers/system.py", line 263, in action_run
    returns=self.resource.returns)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 72, in inner
    result = function(command, **kwargs)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 102, in checked_call
    tries=tries, try_sleep=try_sleep, timeout_kill_strategy=timeout_kill_strategy, returns=returns)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 150, in _call_wrapper
    result = _call(command, **kwargs_copy)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 314, in _call
    raise ExecutionFailed(err_msg, code, out, err)
resource_management.core.exceptions.ExecutionFailed: Execution of 'export SLUGIFY_USES_TEXT_UNIDECODE=yes && pip install --upgrade  --ignore-installed apache-airflow[all]==1.10.0' returned 1. DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting apache-airflow[all]==1.10.0
  Downloading apache-airflow-1.10.0.tar.gz (4.3 MB)
Collecting alembic<0.9,>=0.8.3
  Downloading alembic-0.8.10.tar.gz (976 kB)
Collecting bleach==2.1.2
  Downloading bleach-2.1.2-py2.py3-none-any.whl (27 kB)
Collecting configparser<3.6.0,>=3.5.0
  Downloading configparser-3.5.3-py2-none-any.whl (21 kB)
Collecting croniter<0.4,>=0.3.17
  Downloading croniter-0.3.34-py2.py3-none-any.whl (19 kB)
Collecting dill<0.3,>=0.2.2
  Downloading dill-0.2.9.tar.gz (150 kB)
Collecting flask<0.13,>=0.12.4
  Downloading Flask-0.12.5-py2.py3-none-any.whl (81 kB)
Collecting flask-appbuilder<2.0.0,>=1.11.1
  Downloading Flask-AppBuilder-1.13.1.tar.gz (1.5 MB)
Collecting flask-admin==1.4.1
  Downloading Flask-Admin-1.4.1.tar.gz (922 kB)
Collecting flask-caching<1.4.0,>=1.3.3
  Downloading Flask_Caching-1.3.3-py2.py3-none-any.whl (15 kB)
Collecting flask-login==0.2.11
  Downloading Flask-Login-0.2.11.tar.gz (11 kB)
Collecting flask-swagger==0.2.13
  Downloading flask-swagger-0.2.13.tar.gz (8.0 kB)
Collecting flask-wtf<0.15,>=0.14.2
  Downloading Flask_WTF-0.14.3-py2.py3-none-any.whl (13 kB)
Collecting funcsigs==1.0.0
  Downloading funcsigs-1.0.0-py2.py3-none-any.whl (17 kB)
Collecting future<0.17,>=0.16.0
  Downloading future-0.16.0.tar.gz (824 kB)
Collecting gitpython>=2.0.2
  Downloading GitPython-2.1.15-py2.py3-none-any.whl (452 kB)
Collecting gunicorn<20.0,>=19.4.0
  Downloading gunicorn-19.10.0-py2.py3-none-any.whl (113 kB)
Collecting iso8601>=0.1.12
  Downloading iso8601-0.1.13-py2.py3-none-any.whl (9.3 kB)
Collecting jinja2<2.9.0,>=2.7.3
  Downloading Jinja2-2.8.1-py2.py3-none-any.whl (264 kB)
Collecting lxml<4.0,>=3.6.0
  Downloading lxml-3.8.0-cp27-cp27mu-manylinux1_x86_64.whl (6.8 MB)
Collecting markdown<3.0,>=2.5.2
  Downloading Markdown-2.6.11-py2.py3-none-any.whl (78 kB)
Collecting pandas<1.0.0,>=0.17.1
  Downloading pandas-0.24.2-cp27-cp27mu-manylinux1_x86_64.whl (10.1 MB)
Collecting pendulum==1.4.4
  Downloading pendulum-1.4.4.tar.gz (74 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting psutil<5.0.0,>=4.2.0
  Downloading psutil-4.4.2.tar.gz (1.8 MB)
Collecting pygments<3.0,>=2.0.1
  Downloading Pygments-2.5.2-py2.py3-none-any.whl (896 kB)
Collecting python-daemon<2.2,>=2.1.1
  Downloading python_daemon-2.1.2-py2.py3-none-any.whl (19 kB)
Collecting python-dateutil<3,>=2.3
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting python-nvd3==0.15.0
  Downloading python-nvd3-0.15.0.tar.gz (31 kB)
Collecting requests<3,>=2.5.1
  Downloading requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting setproctitle<2,>=1.1.8
  Downloading setproctitle-1.1.10.tar.gz (24 kB)
Collecting sqlalchemy<1.2.0,>=1.1.15
  Downloading SQLAlchemy-1.1.18.tar.gz (5.3 MB)
Collecting tabulate<0.8.0,>=0.7.5
  Downloading tabulate-0.7.7-py2.py3-none-any.whl (31 kB)
Collecting tenacity==4.8.0
  Downloading tenacity-4.8.0-py2.py3-none-any.whl (27 kB)
Collecting thrift>=0.9.2
  Downloading thrift-0.13.0.tar.gz (59 kB)
Collecting tzlocal>=1.4
  Downloading tzlocal-2.1-py2.py3-none-any.whl (16 kB)
Collecting unicodecsv>=0.14.1
  Downloading unicodecsv-0.14.1.tar.gz (10 kB)
Collecting werkzeug<0.15.0,>=0.14.1
  Downloading Werkzeug-0.14.1-py2.py3-none-any.whl (322 kB)
Collecting zope.deprecation<5.0,>=4.0
  Downloading zope.deprecation-4.4.0-py2.py3-none-any.whl (10 kB)
Collecting sendgrid>=5.2.0
  Downloading sendgrid-6.4.7.tar.gz (47 kB)
Collecting click
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting freezegun
  Downloading freezegun-0.3.15-py2.py3-none-any.whl (14 kB)
Collecting jira
  Downloading jira-2.0.0-py2.py3-none-any.whl (57 kB)
Collecting mock
  Downloading mock-3.0.5-py2.py3-none-any.whl (25 kB)
Collecting mongomock
  Downloading mongomock-3.20.0-py2.py3-none-any.whl (51 kB)
Collecting moto==1.1.19
  Downloading moto-1.1.19-py2.py3-none-any.whl (446 kB)
Collecting nose
  Downloading nose-1.3.7-py2-none-any.whl (154 kB)
Collecting nose-ignore-docstring==0.2
  Downloading nose-ignore-docstring-0.2.tar.gz (1.9 kB)
Collecting nose-timer
  Downloading nose-timer-1.0.0.tar.gz (8.6 kB)
Collecting parameterized
  Downloading parameterized-0.7.4-py2.py3-none-any.whl (25 kB)
Collecting paramiko
  Downloading paramiko-2.7.2-py2.py3-none-any.whl (206 kB)
Collecting pysftp
  Downloading pysftp-0.2.9.tar.gz (25 kB)
Collecting pywinrm
  Downloading pywinrm-0.4.1.tar.gz (36 kB)
Collecting qds-sdk>=1.9.6
  Downloading qds_sdk-1.16.0.tar.gz (75 kB)
Collecting rednose
  Downloading rednose-1.3.0.tar.gz (10 kB)
Collecting requests_mock
  Downloading requests_mock-1.8.0-py2.py3-none-any.whl (23 kB)
Collecting psycopg2-binary>=2.7.4
  Downloading psycopg2_binary-2.8.6-cp27-cp27mu-manylinux1_x86_64.whl (2.9 MB)
Collecting mysqlclient>=1.3.6
  Downloading mysqlclient-1.4.6.tar.gz (85 kB)
Collecting hmsclient>=0.1.0
  Downloading hmsclient-0.1.1.tar.gz (84 kB)
Collecting pyhive>=0.6.0
  Downloading PyHive-0.6.3.tar.gz (41 kB)
Collecting pymssql>=2.1.1
  Downloading pymssql-2.1.5-cp27-cp27mu-manylinux1_x86_64.whl (1.1 MB)
Collecting snakebite>=2.7.8
  Downloading snakebite-2.11.0.tar.gz (78 kB)
Collecting vertica-python>=0.5.1
  Downloading vertica_python-1.0.0-py2.py3-none-any.whl (167 kB)
Collecting cloudant<2.0,>=0.5.9
  Downloading cloudant-0.5.10-py2-none-any.whl (10 kB)
Collecting pydruid>=0.4.1
  Downloading pydruid-0.6.1.tar.gz (43 kB)
Collecting pinotdb>=0.1.1
  Downloading pinotdb-0.3.3-py2.py3-none-any.whl (12 kB)
Collecting cassandra-driver>=3.13.0
  Downloading cassandra_driver-3.24.0-cp27-cp27mu-manylinux1_x86_64.whl (3.5 MB)
Collecting pymongo>=3.6.0
  Downloading pymongo-3.11.0-cp27-cp27mu-manylinux1_x86_64.whl (487 kB)
Collecting sphinx>=1.2.3
  Downloading Sphinx-1.8.5-py2.py3-none-any.whl (3.1 MB)
Collecting sphinx-argparse>=0.1.13
  Downloading sphinx-argparse-0.2.5.tar.gz (12 kB)
Collecting sphinx-rtd-theme>=0.1.6
  Downloading sphinx_rtd_theme-0.5.0-py2.py3-none-any.whl (10.8 MB)
Collecting Sphinx-PyPI-upload>=0.2.1
  Downloading Sphinx-PyPI-upload-0.2.1.tar.gz (4.6 kB)
Collecting pysmbclient>=0.1.3
  Downloading PySmbClient-0.1.5.tar.gz (6.3 kB)
Collecting boto3>=1.7.0
  Downloading boto3-1.15.9-py2.py3-none-any.whl (129 kB)
Collecting slackclient>=1.0.0
  Downloading slackclient-1.3.2.tar.gz (16 kB)
Collecting cryptography>=0.9.3
  Downloading cryptography-3.1.1-cp27-cp27mu-manylinux2010_x86_64.whl (2.6 MB)
Collecting cx_Oracle>=5.1.2
  Downloading cx_Oracle-7.3.0-cp27-cp27mu-manylinux1_x86_64.whl (728 kB)
Collecting docker>=2.0.0
  Downloading docker-4.3.1-py2.py3-none-any.whl (145 kB)
Collecting kubernetes>=3.0.0
  Downloading kubernetes-11.0.0.tar.gz (724 kB)
Collecting celery<4.2.0,>=4.1.1
  Downloading celery-4.1.1-py2.py3-none-any.whl (394 kB)
Collecting flower<1.0,>=0.7.3
  Downloading flower-0.9.5-py2.py3-none-any.whl (459 kB)
Collecting azure-storage>=0.34.0
  Downloading azure-storage-0.37.0.zip (4.3 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_ecujg/azure-storage/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_ecujg/azure-storage/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-YhR27x
         cwd: /tmp/pip-install-_ecujg/azure-storage/
    Complete output (19 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_ecujg/azure-storage/setup.py", line 55, in <module>
        raise RuntimeError(message)
    RuntimeError:
    
    Starting with v0.37.0, the 'azure-storage' meta-package is deprecated and cannot be installed anymore.
    Please install the service specific packages prefixed by `azure` needed for your application.
    
    The complete list of available packages can be found at:
    https://aka.ms/azsdk/python/all
    
    Here's a non-exhaustive list of common packages:
    
    - [azure-storage-blob](https://pypi.org/project/azure-storage-blob) : Blob storage client
    - [azure-storage-file-share](https://pypi.org/project/azure-storage-file-share) : Storage file share client
    - [azure-storage-file-datalake](https://pypi.org/project/azure-storage-file-datalake) : ADLS Gen2 client
    - [azure-storage-queue](https://pypi.org/project/azure-storage-queue): Queue storage client
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
stdout:   /var/lib/ambari-agent/data/output-55.txt
2020-09-30 19:34:15,971 - Stack Feature Version Info: Cluster Stack=3.0, Command Stack=None, Command Version=None -> 3.0
2020-09-30 19:34:16,037 - Using hadoop conf dir: /usr/hdp/current/hadoop-client/conf
2020-09-30 19:34:16,043 - Group['hdfs'] {}
2020-09-30 19:34:16,056 - Group['hadoop'] {}
2020-09-30 19:34:16,057 - Group['users'] {}
2020-09-30 19:34:16,058 - User['zookeeper'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2020-09-30 19:34:16,061 - User['ams'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2020-09-30 19:34:16,065 - User['ambari-qa'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop', 'users'], 'uid': None}
2020-09-30 19:34:16,080 - User['hdfs'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hdfs', 'hadoop'], 'uid': None}
2020-09-30 19:34:16,082 - File['/var/lib/ambari-agent/tmp/changeUid.sh'] {'content': StaticFile('changeToSecureUid.sh'), 'mode': 0555}
2020-09-30 19:34:16,099 - Execute['/var/lib/ambari-agent/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa 0'] {'not_if': '(test $(id -u ambari-qa) -gt 1000) || (false)'}
2020-09-30 19:34:16,155 - Skipping Execute['/var/lib/ambari-agent/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa 0'] due to not_if
2020-09-30 19:34:16,155 - Group['hdfs'] {}
2020-09-30 19:34:16,156 - User['hdfs'] {'fetch_nonlocal_groups': True, 'groups': ['hdfs', 'hadoop', u'hdfs']}
2020-09-30 19:34:16,158 - FS Type: HDFS
2020-09-30 19:34:16,158 - Directory['/etc/hadoop'] {'mode': 0755}
2020-09-30 19:34:16,338 - File['/usr/hdp/current/hadoop-client/conf/hadoop-env.sh'] {'content': InlineTemplate(...), 'owner': 'hdfs', 'group': 'hadoop'}
2020-09-30 19:34:16,341 - Directory['/var/lib/ambari-agent/tmp/hadoop_java_io_tmpdir'] {'owner': 'hdfs', 'group': 'hadoop', 'mode': 01777}
2020-09-30 19:34:16,575 - Repository['HDP-UTILS-1.1.0.22-repo-1'] {'append_to_file': False, 'base_url': 'http://hdp.hadoop.com/HDP-UTILS/centos7/1.1.0.22/', 'action': ['create'], 'components': [u'HDP-UTILS', 'main'], 'repo_template': '[{{repo_id}}]\nname={{repo_id}}\n{% if mirror_list %}mirrorlist={{mirror_list}}{% else %}baseurl={{base_url}}{% endif %}\n\npath=/\nenabled=1\ngpgcheck=0', 'repo_file_name': 'ambari-hdp-1', 'mirror_list': None}
2020-09-30 19:34:16,625 - File['/etc/yum.repos.d/ambari-hdp-1.repo'] {'content': '[HDP-UTILS-1.1.0.22-repo-1]\nname=HDP-UTILS-1.1.0.22-repo-1\nbaseurl=http://hdp.hadoop.com/HDP-UTILS/centos7/1.1.0.22/\n\npath=/\nenabled=1\ngpgcheck=0'}
2020-09-30 19:34:16,627 - Writing File['/etc/yum.repos.d/ambari-hdp-1.repo'] because contents don't match
2020-09-30 19:34:16,628 - Repository['HDP-3.0-repo-1'] {'append_to_file': True, 'base_url': 'http://hdp.hadoop.com/HDP/centos7/3.0.0.0-1634/', 'action': ['create'], 'components': [u'HDP', 'main'], 'repo_template': '[{{repo_id}}]\nname={{repo_id}}\n{% if mirror_list %}mirrorlist={{mirror_list}}{% else %}baseurl={{base_url}}{% endif %}\n\npath=/\nenabled=1\ngpgcheck=0', 'repo_file_name': 'ambari-hdp-1', 'mirror_list': None}
2020-09-30 19:34:16,666 - File['/etc/yum.repos.d/ambari-hdp-1.repo'] {'content': '[HDP-UTILS-1.1.0.22-repo-1]\nname=HDP-UTILS-1.1.0.22-repo-1\nbaseurl=http://hdp.hadoop.com/HDP-UTILS/centos7/1.1.0.22/\n\npath=/\nenabled=1\ngpgcheck=0\n[HDP-3.0-repo-1]\nname=HDP-3.0-repo-1\nbaseurl=http://hdp.hadoop.com/HDP/centos7/3.0.0.0-1634/\n\npath=/\nenabled=1\ngpgcheck=0'}
2020-09-30 19:34:16,667 - Writing File['/etc/yum.repos.d/ambari-hdp-1.repo'] because contents don't match
2020-09-30 19:34:16,669 - Repository['HDP-3.0-GPL-repo-1'] {'append_to_file': True, 'base_url': 'http://hdp.hadoop.com/HDP-GPL/centos7/3.0.0.0-1634/', 'action': ['create'], 'components': [u'HDP-GPL', 'main'], 'repo_template': '[{{repo_id}}]\nname={{repo_id}}\n{% if mirror_list %}mirrorlist={{mirror_list}}{% else %}baseurl={{base_url}}{% endif %}\n\npath=/\nenabled=1\ngpgcheck=0', 'repo_file_name': 'ambari-hdp-1', 'mirror_list': None}
2020-09-30 19:34:16,693 - File['/etc/yum.repos.d/ambari-hdp-1.repo'] {'content': '[HDP-UTILS-1.1.0.22-repo-1]\nname=HDP-UTILS-1.1.0.22-repo-1\nbaseurl=http://hdp.hadoop.com/HDP-UTILS/centos7/1.1.0.22/\n\npath=/\nenabled=1\ngpgcheck=0\n[HDP-3.0-repo-1]\nname=HDP-3.0-repo-1\nbaseurl=http://hdp.hadoop.com/HDP/centos7/3.0.0.0-1634/\n\npath=/\nenabled=1\ngpgcheck=0\n[HDP-3.0-GPL-repo-1]\nname=HDP-3.0-GPL-repo-1\nbaseurl=http://hdp.hadoop.com/HDP-GPL/centos7/3.0.0.0-1634/\n\npath=/\nenabled=1\ngpgcheck=0'}
2020-09-30 19:34:16,694 - Writing File['/etc/yum.repos.d/ambari-hdp-1.repo'] because contents don't match
2020-09-30 19:34:16,706 - Package['unzip'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2020-09-30 19:34:17,258 - Skipping installation of existing package unzip
2020-09-30 19:34:17,258 - Package['curl'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2020-09-30 19:34:17,318 - Skipping installation of existing package curl
2020-09-30 19:34:17,318 - Package['hdp-select'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2020-09-30 19:34:17,365 - Skipping installation of existing package hdp-select
2020-09-30 19:34:17,389 - The repository with version 3.0.0.0-1634 for this command has been marked as resolved. It will be used to report the version of the component which was installed
2020-09-30 19:34:17,417 - Skipping stack-select on AIRFLOW because it does not exist in the stack-select package structure.
2020-09-30 19:34:18,100 - Package['krb5-devel'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2020-09-30 19:34:18,897 - Skipping installation of existing package krb5-devel
2020-09-30 19:34:18,899 - Package['python-devel'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2020-09-30 19:34:18,940 - Skipping installation of existing package python-devel
2020-09-30 19:34:18,942 - Package['sqlite-devel'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2020-09-30 19:34:18,987 - Skipping installation of existing package sqlite-devel
2020-09-30 19:34:18,989 - Package['openssl-devel'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2020-09-30 19:34:19,034 - Skipping installation of existing package openssl-devel
2020-09-30 19:34:19,037 - Package['mysql-devel'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2020-09-30 19:34:19,081 - Installing package mysql-devel ('/usr/bin/yum -y install mysql-devel')
2020-09-30 19:35:30,817 - Package['python-pip'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2020-09-30 19:35:30,867 - Installing package python-pip ('/usr/bin/yum -y install python-pip')
2020-09-30 19:36:11,842 - Package['zlib-devel'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2020-09-30 19:36:12,201 - Skipping installation of existing package zlib-devel
2020-09-30 19:36:12,229 - Package['bzip2-devel'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2020-09-30 19:36:12,326 - Installing package bzip2-devel ('/usr/bin/yum -y install bzip2-devel')
2020-09-30 19:36:36,323 - Package['ncurses-devel'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2020-09-30 19:36:36,368 - Installing package ncurses-devel ('/usr/bin/yum -y install ncurses-devel')
2020-09-30 19:37:05,232 - Package['wget'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2020-09-30 19:37:05,322 - Skipping installation of existing package wget
2020-09-30 19:37:05,324 - Package['which'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2020-09-30 19:37:05,494 - Skipping installation of existing package which
2020-09-30 19:37:05,508 - Package['gcc-c++'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2020-09-30 19:37:05,585 - Installing package gcc-c++ ('/usr/bin/yum -y install gcc-c++')
2020-09-30 19:37:47,966 - Package['cyrus-sasl-devel'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2020-09-30 19:37:48,094 - Installing package cyrus-sasl-devel ('/usr/bin/yum -y install cyrus-sasl-devel')
2020-09-30 19:38:20,699 - Installing Airflow Service
2020-09-30 19:38:20,700 - Execute['pip install --upgrade  pip'] {}
2020-09-30 19:38:38,350 - Execute['pip install --upgrade  setuptools'] {}
2020-09-30 19:38:55,480 - Execute['pip install --upgrade  docutils pytest-runner Cython==0.28'] {}
2020-09-30 19:39:28,937 - Execute['export SLUGIFY_USES_TEXT_UNIDECODE=yes && pip install --upgrade  --ignore-installed apache-airflow[all]==1.10.0'] {}
2020-09-30 19:43:35,661 - The repository with version 3.0.0.0-1634 for this command has been marked as resolved. It will be used to report the version of the component which was installed
2020-09-30 19:43:35,710 - Skipping stack-select on AIRFLOW because it does not exist in the stack-select package structure.

Command failed after 1 tries
